### ISSUE TITLE
Outdated certbot

### ISSUE THREAD

**Issue by namedgraph** [pslobo/dockerized-certbot#3]
How do we upgrade the certbot version?

    docker container run -it palobo/certbot --version
    certbot 0.21.0.dev0

TLS-SNI-01 validation is deprecated, getting rid of it [requires certbot 0.28](
https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210).

**Comment by azawawi** [comment]
@pslobo Could you please upgrade this docker image?

**Comment by namedgraph** [comment]
In the meanwhile I've [forked this repo](https://github.com/AtomGraph/dockerized-certbot) and built a new image on Docker Hub which includes certbot 0.33: [atomgraph/certbot](https://hub.docker.com/r/atomgraph/certbot)

**Comment by pslobo** [comment]
Hey all, sorry about this, but given that there are already [official builds](https://hub.docker.com/r/certbot/certbot) of Certbot, it seems pointless to maintain mine, especially since it isn't doing anything the official one isn't.

Nonetheless, if you really need mine, then I'll look into updating it sure, but I would recommend you move to the official builds.
